export const Consumables = [
    ['Observer_Ward','侦察守卫'],
    ['Blood_Grenade', '血腥榴弹'],
    ['Clarity', '净化药水'],
    ['Sentry_Ward', '岗哨守卫'],
    ['Smoke_of_Deceit', '诡计之雾'],
    ['Enchanted_Mango', '魔法芒果'],
    ['Faerie_Fire', '仙灵之火'],
    ['Dust_of_Appearance', '显影之尘'],
    ['Tango', '树之祭祀'],
    ['Healing_Salve', '治疗药膏'],
    ['Town_Portal_Scroll', '回城卷轴'],
    ['Bottle', '魔瓶'],
    ['Aghanims_Shard', '阿哈利姆魔晶'],
];

export const Attributes = [
    ['Iron_Branch', '铁树枝干'],
    ['Gauntlets_of_Strength', '力量手套'],
    ['Mantle_of_Intelligence', '智力斗篷'],
    ['Slippers_of_Agility', '敏捷便鞋'],
    ['Circlet', '圆环'],
    ['Band_of_Elvenskin', '精灵腰带'],
    ['Belt_of_Strength', '力量腰带'],
    ['Robe_of_the_Magi', '魔力斗篷'],
    ['Crown', '王冠'],
    ['Blade_of_Alacrity', '敏捷之刃'],
    ['Ogre_Axe', '食人魔之斧'],
    ['Staff_of_Wizardry', '魔力法杖'],
    ['Diadem','宝冕']
];

export const Equipment = [
    ['Quelling_Blade', '压制之刃'],
    ['Ring_of_Protection', '守护指环'],
    ['Infused_Raindrops', '凝魂之露'],
    ['Orb_of_Venom', '淬毒之球'],
    ['Blight_Stone', '枯萎之石'],
    ['Blades_of_Attack', '攻击之爪'],
    ['Gloves_of_Haste', '加速手套'],
    ['Chainmail', '锁子甲'],
    ['Javelin', '标枪'],
    ['Helm_of_Iron_Will', '铁意头盔'],
    ['Blitz_Knuckles', '闪电指套'],
    ['Broadsword', '阔剑'],
    ['Claymore', '大剑'],
    ['Mithril_Hammer', '秘银锤'],
];

export const Miscellaneous = [
    ['Ring_of_Regen', '回复戒指'],
    ['Sages_Mask', '贤者面罩'],
    ['Fluffy_Hat', '毛毛帽'],
    ['Wind_Lace', '风灵之纹'],
    ['Magic_Stick', '魔棒'],
    ['Boots_of_Speed', '速度之靴'],
    ['Ring_of_Health', '生命指环'],
    ['Void_Stone', '虚无宝石'],
    ['Voodoo_Mask', '巫毒面具'],
    ['Cloak', '抗魔斗篷'],
    ['Gem_of_True_Sight', '真视宝石'],
    ['Morbid_Mask', '吸血面具'],
    ['Shadow_Amulet', '暗影护符'],
    ['Ghost_Scepter', '幽魂权杖'],
    ['Blink_Dagger', '闪烁匕首'],
];

export const SecretShop = [
    ['Energy_Booster', '能量之球'],
    ['Vitality_Booster', '活力之球'],
    ['Point_Booster', '精气之球'],
    ['Cornucopia', '丰饶之环'],
    ['Talisman_of_Evasion', '闪避护符'],
    ['Platemail', '板甲'],
    ['Ring_of_Tarrasque', '恐鳌之戒'],
    ['Tiara_of_Selemene', '赛莉蒙妮之冠'],
    ['Hyperstone', '振奋宝石'],
    ['Demon_Edge', '恶魔刀锋'],
    ['Eaglesong', '鹰歌弓'],
    ['Mystic_Staff', '神秘法杖'],
    ['Reaver', '掠夺者之斧'],
    ['Ultimate_Orb', '极限法球'],
    ['Sacred_Relic', '圣者遗物'],
];

export const Accessories = [
    ['Magic_Stick', '魔杖'],
    ['Bracer', '护腕'],
    ['Null_Talisman', '空灵挂件'],
    ['Wraith_Band', '怨灵系带'],
    ['Soul_Ring', '灵魂之戒'],
    ['Orb_of_Corrosion', '腐蚀之球'],
    ['Falcon_Blade', '猎鹰战刃'],
    ['Perseverance', '坚韧球'],
    ['Power_Treads', '动力鞋'],
    ['Phase_Boots', '相位鞋'],
    ['Oblivion_Staff', '空明杖'],
    ['Mask_of_Madness', '疯狂面具'],
    ['Hand_of_Midas', '迈达斯之手'],
    ['Boots_of_Travel_1', '远行鞋'],
    ['Helm_of_the_Dominator', '支配头盔'],
    ['Moon_Shard', '银月之晶'],
];

export const Support = [
    ['Buckler', '玄冥盾牌'],
    ['Headdress', '恢复头巾'],
    ['Ring_of_Basilius', '王者之戒'],
    ['Urn_of_Shadows', '影之灵龛'],
    ['Tranquil_Boots', '静谧之鞋'],
    ['Arcane_Boots', '奥鞋'],
    ['Pavise', '长盾'],
    ['Drum_of_Endurance', '韧鼓'],
    ['Mekansm', '梅肯斯姆'],
    ['Vladmirs_Offering', '弗拉迪米尔的祭品'],
    ['Holy_Locket', '圣洁吊坠'],
    ['Spirit_Vessel', '魂之灵瓮'],
    ['Pipe_of_Insight', '洞察烟斗'],
    ['Boots_of_Bearing','宽容之靴'],
    ['Guardian_Greaves', '卫士胫甲'],
    ['Parasma', '圣斧'],
];

export const Magical = [
    ['Veil_of_Discord', '纷争面纱'],
    ['Glimmer_Cape', '微光披风'],
    ['Force_Staff', '原力法杖'],
    ['Rod_of_Atos', '阿托斯之棍'],
    ['Aether_Lens', '以太透镜'],
    ['Euls_Scepter_of_Divinity', 'EUL的神圣法杖'],
    ['Solar_Crest', '炎阳纹章'],
    ['Witch_Blade', '巫师之刃'],
    ['Dagon_1', '达贡之神力'],
    ['Orchid_Malevolence', '紫怨'],
    ['Aghanims_Scepter', '阿哈利姆神杖'],
    ['Octarine_Core', '玲珑心'],
    ['Refresher_Orb', '刷新球'],
    ['Scythe_of_Vyse', '邪恶镰刀'],
    ['Gleipnir', '缚灵索'],
    ['Wind_Waker', '风之杖'],
];

export const Armor = [
    ['Vanguard', '先锋盾'],
    ['Blade_Mail', '刃甲'],
    ['Aeon_Disk', '永恒之盘'],
    ['Soul_Booster', '振魂石'],
    ['Eternal_Shroud', '永世法衣'],
    ['Crimson_Guard', '赤红甲'],
    ['Lotus_Orb', '清莲宝珠'],
    ['Black_King_Bar', '黑皇杖'],
    ['Bloodstone', '血精石'],
    ['Hurricane_Pike', '飓风长戟'],
    ['Manta_Style', '幻影斧'],
    ['Linkens_Sphere', '林肯法球'],
    ['Assault_Cuirass', '强袭胸甲'],
    ['Shivas_Guard', '希瓦的守护'],
    ['Heart_of_Tarrasque', '恐鳌之心'],
    ['Helm_of_the_Overlord', '统御头盔'],
];

export const Weapons = [
    ['Crystalys', '水晶剑'],
    ['Armlet_of_Mordiggian', '莫迪基安的臂章'],
    ['Meteor_Hammer', '陨星锤'],
    ['Skull_Basher', '裂颅锤'],
    ['Shadow_Blade', '影刃'],
    ['Desolator', '黯灭'],
    ['Battle_Fury', '狂战斧'],
    ['Nullifier', '否决坠饰'],
    ['Monkey_King_Bar', '金箍棒'],
    ['Radiance', '辉耀'],
    ['Revenants_Brooch', '亡灵胸针'],
    ['Khanda', '绝刃'],
    ['Daedalus', '代达罗斯之殇'],
    ['Ethereal_Blade', '虚灵之刃'],
    ['Butterfly', '蝴蝶'],
    ['Silver_Edge', '白银之锋'],
    ['Divine_Rapier', '圣剑'],
    ['Disperser', '散魂剑'],
    ['Abyssal_Blade', '深渊之刃'],
    ['Bloodthorn', '血棘'],
];

export const Artifacts = [
    ['Dragon_Lance', '魔龙枪'],
    ['Kaya', '慧光'],
    ['Sange', '散华'],
    ['Yasha', '夜叉'],
    ['Phylactery', '圣器'],
    ['Diffusal_Blade', '净魂之刃'],
    ['Echo_Sabre', '回音战刃'],
    ['Mage_Slayer', '法师克星'],
    ['Maelstrom', '漩涡'],
    ['Heavens_Halberd', '天堂之戟'],
    ['Yasha_and_Kaya', '慧夜对剑'],
    ['Kaya_and_Sange', '散慧对剑'],
    ['Sange_and_Yasha', '散夜对剑'],
    ['Harpoon', '鱼叉'],
    ['Satanic', '撒旦之邪力'],
    ['Eye_of_Skadi', '斯嘉蒂之眼'],
    ['Mjollnir', '雷神之锤'],
    ['Arcane_Blink', '奥秘闪光'],
    ['Overwhelming_Blink', '盛势闪光'],
    ['Swift_Blink', '迅疾闪光'],
];

export const Tier1 = [
    ['Arcane_Ring', '奥数指环'],
    ['Broom_Handle', '扫帚柄'],
    ['Duelist_Gloves', '决斗家手套'],
    ['Faded_Broach', '暗淡胸针'],
    ['Fairys_Trinket', '仙灵饰品'],
    ['Lance_of_Pursuit', '追击之矛'],
    ['Occult_Bracelet', '玄奥手镯'],
    ['Pig_Pole', '豚杆'],
    ['Royal_Jelly', '蜂王浆'],
    ['Safety_Bubble', '安全泡泡'],
    ['Seeds_of_Serenity', '宁静种籽'],
    ['Spark_of_Courage', '勇气之光'],
    ['Trusty_Shovel', '可靠铲子'],
];

export const Tier2 = [
    ['Bullwhip', '凌厉长鞭'],
    ['Dragon_Scale', '炎龙之鳞'],
    ['Eye_of_the_Vizier', '维齐尔之眼'],
    ['Gossamer_Cape', '蛛丝斗篷'],
    ['Grove_Bow', '林野长弓'],
    ['Light_Collector', '集光器'],
    ['Orb_of_Destruction', '毁灭灵球'],
    ['Philosophers_Stone', '贤者石'],
    ['Pupils_Gift', '学徒之礼'],
    ['Specialists_Array', '行家阵列'],
    ['Vambrace', '臂甲'],
    ['Vampire_Fangs', '吸血鬼獠牙'],
    ['Whisper_of_the_Dread', '邪道私语'],
];

export const Tier3 = [
    ['Ceremonial_Robe', '祭礼长袍'],
    ['Cloak_of_Flames', '火焰斗篷'],
    ['Craggy_Coat', '崎岖外衣'],
    ['Dandelion_Amulet', '蒲公英护符'],
    ['Defiant_Shell', '不羁甲壳'],
    ['Doubloon', '双面币'],
    ['Elven_Tunic', '精灵外衣'],
    ['Enchanted_Quiver', '魔力箭袋'],
    ['Nemesis_Curse', '天诛之咒'],
    ['Ogre_Seal_Totem', '食人魔海豹图腾'],
    ['Paladin_Sword', '骑士剑'],
    ['Psychic_Headband', '通灵头带'],
    ['Vindicators_Axe', '正义之斧'],
];

export const Tier4 = [
    ['Ancient_Guardian', '遗迹守护者'],
    ['Ascetics_Cap', '简朴短帽'],
    ['Avianas_Feather', '艾维娜之羽'],
    ['Havoc_Hammer', '豪杰巨锤'],
    ['Martyrs_Plate', '烈士鳞甲'],
    ['Mind_Breaker', '智灭'],
    ['Ninja_Gear', '忍者用具'],
    ['Rattlecage', '回响之笼'],
    ['Stormcrafter', '风暴宝器'],
    ['Telescope', '望远镜'],
    ['Timeless_Relic', '永恒遗物'],
    ['Trickster_Cloak', '欺诈师斗篷'],
];

export const Tier5 = [
    ['Apex', '极'],
    ['Arcanists_Armor', '秘术师铠甲'],
    ['Book_of_Shadows', '暗影邪典'],
    ['Book_of_the_Dead', '冥灵书'],
    ['Force_Boots', '原力靴'],
    ['Giants_Ring', '巨人之戒'],
    ['Magic_Lamp', '神妙明灯'],
    ['Mirror_Shield', '神镜盾'],
    ['Pirate_Hat', '海盗帽'],
    ['Seer_Stone', '先哲之石'],
    ['Stygian_Desolator', '寂灭'],
    ['Unwavering_Condition', '坚毅之件'],
];