/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/yellow_gem/diggers_divining_rod_gem_topaz2.glb 
*/
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Yellow_Gem(props) {
  const { scene } = useGLTF('http://localhost:3001/assets/models/yellow_gem/diggers_divining_rod_gem_topaz2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]} scale={0.05} position={[0, 1, -0.3]}>
        <primitive object={nodes.gem_03} />
      </group>
      <skinnedMesh geometry={nodes.diggers_divining_rod_gem_topaz2vmdl_cdiggers_divining_rod_gem_topaz2_model.geometry} material={materials.diggers_divining_rod_gems} skeleton={nodes.diggers_divining_rod_gem_topaz2vmdl_cdiggers_divining_rod_gem_topaz2_model.skeleton} />
    </group>
  )
}
