export const NPCs = {
    creeps: [
        {
            NPCId: 1,
            NPCName: 'melee creep',
            NPCCNName: '近战小兵',
            NPCLevel: 3,
            NPCIcon: 'npc/npc_dota_hero_creep_dire_png.png',
            InitHealth: 550,
            InitMana: 0,
            InitHealthRecover: 0.5,
            InitManaRecover: 0,
            InitArmor: 2,
            InitMagicResist: 0,
            DamageMin: 19,
            DamageMax: 23,
            AttackType: 0,
            NPCDescription: '在15:00时，每波兵近战兵数量提升1。在30:00时，每波兵近战兵数量再提升1。在45:00时，每波兵近战兵数量再提升1，达到每波6个近战兵。每过450秒，远程兵的生命值上限提升12、攻击力提升1。',
        },
        {
            NPCId: 2,
            NPCName: 'ranged creep',
            NPCCNName: '远程小兵',
            NPCLevel: 1,
            NPCIcon: 'npc/npc_dota_hero_creep_radiant_png.png',
            InitHealth: 300,
            InitMana: 500,
            InitHealthRecover: 2,
            InitManaRecover: 0.75,
            InitArmor: 0,
            InitMagicResist: 0,
            DamageMin: 21,
            DamageMax: 26,
            AttackType: 1,
            NPCDescription: '在40：00后，每波兵生成两个远程兵。每过450秒，远程兵的生命值上限提升12、攻击力提升2。',
        },
        {
            NPCId: 3,
            NPCName: 'siege creep',
            NPCCNName: '攻城车',
            NPCLevel: 4,
            NPCIcon: 'npc/Siege_Creep_Dire_icon.webp',
            InitHealth: 935,
            InitMana: 0,
            InitHealthRecover: 0,
            InitManaRecover: 0,
            InitArmor: 0,
            InitMagicResist: 80,
            DamageMin: 35,
            DamageMax: 46,
            AttackType: 1,
            NPCDescription: '第一个攻城车在5：00时生成，生成间隔为300秒。在35：00后，每波兵会生成两个攻城车。当兵营被摧毁时，攻城车攻击力提升16。',
        },
    ],
    n_creeps: [
        {
            NPCId: 4,
            NPCName: 'polar_furbolg_champion',
            NPCCNName: '黄皮熊怪',
            NPCLevel: 5,
            NPCIcon: 'npc/Siege_Creep_Dire_icon.webp',
            InitHealth: 500,
            InitMana: 0,
            InitHealthRecover: 0,
            InitManaRecover: 0,
            InitArmor: 5,
            InitMagicResist: 25,
            DamageMin: 12,
            DamageMax: 15,
            AttackType: 0,
            NPCDescription: '',
        },
        {
            NPCId: 4,
            NPCName: 'polar_furbolg_champion',
            NPCCNName: '黄皮熊怪',
            NPCLevel: 5,
            NPCIcon: 'npc/Siege_Creep_Dire_icon.webp',
            InitHealth: 500,
            InitMana: 0,
            InitHealthRecover: 0,
            InitManaRecover: 0,
            InitArmor: 5,
            InitMagicResist: 25,
            DamageMin: 12,
            DamageMax: 15,
            AttackType: 0,
            NPCDescription: '',
        },
        {
            NPCId: 4,
            NPCName: 'polar_furbolg_champion',
            NPCCNName: '黄皮熊怪',
            NPCLevel: 5,
            NPCIcon: 'npc/Siege_Creep_Dire_icon.webp',
            InitHealth: 500,
            InitMana: 0,
            InitHealthRecover: 0,
            InitManaRecover: 0,
            InitArmor: 5,
            InitMagicResist: 25,
            DamageMin: 12,
            DamageMax: 15,
            AttackType: 0,
            NPCDescription: '',
        },
        {
            NPCId: 4,
            NPCName: 'polar_furbolg_champion',
            NPCCNName: '黄皮熊怪',
            NPCLevel: 5,
            NPCIcon: 'npc/Siege_Creep_Dire_icon.webp',
            InitHealth: 500,
            InitMana: 0,
            InitHealthRecover: 0,
            InitManaRecover: 0,
            InitArmor: 5,
            InitMagicResist: 25,
            DamageMin: 12,
            DamageMax: 15,
            AttackType: 0,
            NPCDescription: '',
        },
    ]
}