create table heros (
	HeroId int auto_increment primary key,
    HeroName varchar(100) not null,
    HeroCNName varchar(100) not null,
    HeroType int not null,
    Image1 varchar(100) default('none.jpg'),
    Image2 varchar(100) default('none.jpg'),
    Image3 varchar(100) default('none.jpg'),
    InitStrength int not null,
    StrengthGrowth float not null,
    InitAgility int not null,
    AgilityGrowth float not null,
    InitIntellignece int not null,
    IntelligenceGrowth float not null,
    InitHealth int not null,
    InitHealthRecover float not null,
    InitMana int not null,
    InitManaRecover float not null,
    InitArmor float not null,
    InitMagicResist float default(25.0),
    DamageMin int not null,
    DamageMax int not null,
    AttackType int not null,
    AttackRange int not null,
    InitAttackSpeed int not null,
    AttackRate float not null,
    AttackAnimation1 float not null,
    AttackAnimation2 float not null,
    ProjectileSpeed float not null,
    MoveSpeed int not null,
    TurnRate float not null,
    DayVision int not null,
    NightVision int not null,
    IsDiable tinyint not null default 0,
    IsEscape tinyint not null default 0,
    IsInitiator tinyint not null default 0,
    IsNuker tinyint not null default 0,
    IsPusher tinyint not null default 0,
    Complixity int not null default 1
);