create table aghanim (
	AghanimId int primary key auto_increment,
	EffectOwner varchar(100) not null,
    AffectSkill1 varchar(100) not null default '',
    Description1 varchar(2000) not null default '',
    IsNewSkill1 tinyint not null default 0,
    IsShard1 tinyint not null default 0,
    ExtraInfo1 varchar(1000) not null default '',
    AffectSkill2 varchar(100) not null default '',
    Description2 varchar(2000) not null default '',
    IsNewSkill2 tinyint not null default 0,
    IsShard2 tinyint not null default 0,
    ExtraInfo2 varchar(1000) not null default '',
    AffectSkill3 varchar(100) not null default '',
    Description3 varchar(2000) not null default '',
    IsNewSkill3 tinyint not null default 0,
    IsShard3 tinyint not null default 0,
    ExtraInfo3 varchar(1000) not null default '',
    AffectSkill4 varchar(100) not null default '',
    Description4 varchar(2000) not null default '',
    IsNewSkill4 tinyint not null default 0,
    IsShard4 tinyint not null default 0,
    ExtraInfo4 varchar(1000) not null default ''
);