create table items (
	ItemId int auto_increment primary key,
    ItemName varchar(100) not null,
    ItemCNName varchar(100) not null,
    ItemImage1 varchar(100) default '',
    ItemImage2 varchar(100) default '',
    PositiveSkill varchar(100) default '',
    NegativeSkill1 varchar(100) default '',
    NegativeSkill2 varchar(100) default '',
    NegativeSkill3 varchar(100) default '',
    ItemExtraInfo varchar(1000) default '',
    ItemDescription varchar(1000) default '',
    Health float default 0,
    Mana float default 0,
    HealthRevocer float default 0,
    ManaRecover float default 0,
    Damage float default 0,
    Strength float default 0,
    Agility float default 0,
    Intelligence float default 0,
    Armor float default 0,
    MagicResist float default 0,
    AttackSpeed float default 0,
    MoveSpeed float default 0,
    MoveSpeedPercentage float default 0,
    CastRange float default 0,
    CDReduce float default 0
);